** 水龙头


** question
 什么是交易确认 
矿工每隔10分钟会将比特币网络中未被记账的交易打包进一个区块，这就完成了一次确认

 比特币找零机制
比特币转账可以一次把多个地址的余额转出，也可以一次转入多个地址。举个栗子，你需要支付给牛牛5个比特币，但是你的A/B/C 3个地址里各有1/2/2个比特币，每个地址的余额都不足以支付5个比特币。这时候，你可以发起一笔转账，同时把A/B/C三个地址共5个比特币转账给牛牛。再举个栗子，如果你的比特币地址有5个比特币，但是你只需要转1个给牛牛。你需要在转账的时候告诉矿工：我有5个比特币，其中1个转给牛牛，另外4个转回给我自己（可以是原地址或创建新的地址）。千万别忘了说哦，不然剩余的4个比特币就全给矿工当手续费了。这就是比特币的找零机制。

 量化交易
量化交易，有时候也称自动化交易，是指以先进的数学模型替代人为的主观判断，极大地减少了投资者情绪波动的影响，避免在市场极度狂热或悲观的情况下做出非理性的投资决策。量化交易有很多种，包括跨平台搬砖、趋势交易、对冲等。跨平台搬砖是指，当不同目标平台价差达到一定金额，在价高的平台卖出，在价低的平台买入。趋势交易会更加复杂一些，它根据趋势的指标来发出卖出和买入的信号。对冲是指同时进行两笔与行情相关、买卖方向相反、数量相当、盈亏相抵的交易，以达到对冲风险的效果。量化交易是成熟交易市场的标志。

 制造信用的机器
区块链并不是新发明的一种技术，而是一系列技术的集成，包括非对称加密技术、时间戳、共识机制等。

 最长区块链
比特币白皮书规定，节点永远认为最长链是正确的区块链，并将持续在它上面延长。所有矿工都在最长链上挖矿，有利于区块链账本的唯一性。如果给你转账的比特币交易不记录在最长链上，你将有可能面临财产损失。怎样算是“最长的区块链”呢？因为全世界的矿工同时在挖矿，有可能同时有2个矿工算出了正确的答案，那么区块链就会形成分叉，剩下的矿工有可能在其中任意一条分叉上继续挖矿，延长区块链。所以我们通常要求在比特币转账被打包之后，还需要经历6个区块的确认，确保矿工不会再回到另一条分叉上挖矿时，才算真正的转账成功。

 区块链分类
区块链按准入机制分成3类：公有链，私有链和联盟链。以后还可能诞生其他类型的区块链。

 共识机制
公有链公开透明。世界上任何个体或者团体都可以在公有链发送交易，且交易能够获得该区块链的有效确认。每个人都可以竞争记账权。比特币区块链就是公有链的典型代表。
联盟链半公开。是某个群体或组织内部使用的区块链，需要预先指定几个节点为记账人，每个区块的生成由所有预选记账人共同决定，其他节点可以交易，但是没有记账权。
私有链则完全封闭。仅采用区块链技术进行记账，记账权并不公开，且只记录内部的交易，由公司或者个人独享。

 区块链记录哪些信息


 扩容

 EOS是什么
EOS是一个区块链开发平台，具有可扩展性强、支持大规模商业应用等特点。首先，EOS 采取DPoS共识算法及其他技术手段预期实现每秒百万级别交易请求，将能够支持数千个商业级的DAPPs。以太坊是一条公链，在以太坊链上运行的每一个应用都会消耗整条链的资源，但EOS 只是区块链基础架构，开发者可以自由地在 EOS 上创建公链，链与链之间不会影响彼此的资源使用，不会出现因个别应用资源消耗巨大而造成网络大面积拥堵。 其次，在 EOS 上转账与运行智能合约并不需要消耗 EOS代币，这将吸引更多的用户

 以太坊开发 evm (以太坊是什么)


 应用 
augur 预测
golem 计算
