** link : https://www.cnblogs.com/edgedance/p/7044753.html

** top explain
*** 第一行：
+ 10:01:23                       — 当前系统时间
+ 126 days, 14:29                — 系统已经运行了126天14小时29分钟（在这期间没有重启过）
+ 2 users                        — 当前有2个用户登录系统
+ load average: 1.15, 1.42, 1.44 — load average后面的三个数分别是1分钟、5分钟、15分钟的负载情况。
+ load average数据是每隔5秒钟检查一次活跃的进程数，然后按特定算法计算出的数值。如果这个数除以逻辑CPU的数量，结果高于5的时候就表明系统在超负荷运转了。

*** 第二行：
+ Tasks                          — 任务（进程），系统现在共有183个进程，其中处于运行中的有1个，182个在休眠（sleep），stoped状态的有0个，zombie状态（僵尸）的有0个。

*** 第三行：cpu状态
+ 6.7% us — 用户空间占用CPU的百分比。
+ 0.4% sy — 内核空间占用CPU的百分比。
+ 0.0% ni — 改变过优先级的进程占用CPU的百分比
+ 92.9% id — 空闲CPU百分比
+ 0.0% wa — IO等待占用CPU的百分比
+ 0.0% hi — 硬中断（Hardware IRQ）占用CPU的百分比
+ 0.0% si — 软中断（Software Interrupts）占用CPU的百分比

*** 第四行：内存状态
+ 8306544k total — 物理内存总量（8GB）
+ 7775876k used — 使用中的内存总量（7.7GB）
+ 530668k free — 空闲内存总量（530M）
+ 79236k buffers — 缓存的内存量 （79M）

*** 第五行：swap交换分区
+ 2031608k total — 交换区总量（2GB）
+ 2556k used — 使用的交换区总量（2.5M）
+ 2029052k free — 空闲交换区总量（2GB）
+ 4231276k cached — 缓冲的交换区总量（4GB）

*** ts
+ 这里要说明的是不能用windows的内存概念理解这些数据，如果按windows的方式此台服务器“危矣”：8G的内存总量只剩下530M的可用内存。Linux的内存管理有其特殊性，复杂点需要一本书来说明，这里只是简单说点和我们传统概念（windows）的不同。

+ 第四行中使用中的内存总量（used）指的是现在系统内核控制的内存数，空闲内存总量（free）是内核还未纳入其管控范围的数量。纳入内核管理的内存不见得都在使用中，还包括过去使用过的现在可以被重复利用的内存，内核并不把这些可被重新使用的内存交还到free中去，因此在linux上free内存会越来越少，但不用为此担心。

+ 如果出于习惯去计算可用内存数，这里有个近似的计算公式：第四行的free + 第四行的buffers + 第五行的cached，按这个公式此台服务器的可用内存：530668+79236+4231276 = 4.7GB。

+ 对于内存监控，在top里我们要时刻监控第五行swap交换分区的used，如果这个数值在不断的变化，说明内核在不断进行内存和swap的数据交换，这是真正的内存不够用了。
